apiVersion: v1
kind: Service
metadata:
  name: devops-sample
spec:
  selector:
    app: devops-sample
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
